<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'PrestaShop\PrestaShop\Core\Security\TokenAuthenticator' shared service.

return $this->privates['PrestaShop\\PrestaShop\\Core\\Security\\TokenAuthenticator'] = new \PrestaShop\PrestaShop\Core\Security\TokenAuthenticator(new \PrestaShopBundle\Security\OAuth2\ResourceServer(new \League\OAuth2\Server\ResourceServer(($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] ?? ($this->privates['PrestaShopBundle\\Security\\OAuth2\\Repository\\AccessTokenRepository'] = new \PrestaShopBundle\Security\OAuth2\Repository\AccessTokenRepository())), new \League\OAuth2\Server\CryptKey('-----BEGIN PUBLIC KEY-----'."\n".'MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsRbdhZpmOlaOjMbTHTpJ'."\n".'uA3jPm9ENC7ojYuF+ulw6KMxKPXsatinvqaRa9XEUz9pV3ZBIj4CsNKx42HW/mNN'."\n".'g/tkvBEesl475pXJnDS7rK443TqfmjaJ95Yk9Wpos/xqngQczDhCy387xZHVOyiK'."\n".'9oVUlSDUsgFXtTuOJflwfy3iIMgFuB6evCZCzBtEmR0JpRiBY3nmkMCD0trff1dj'."\n".'IFP4hApBS22lLUEN2Si0unm/huUD87f1B+q/xtb7vQye9b9UzzOcWD7HJVHvvMRf'."\n".'ATgFgbZGcgiyEim/m4OQsfDwp3tl+xF5+Hf9+T+d2ls50GZdqfZl1Wd/k9yAK89x'."\n".'3QIDAQAB'."\n".'-----END PUBLIC KEY-----'."\n".'')), ($this->privates['security.user.provider.concrete.oauth2'] ?? ($this->privates['security.user.provider.concrete.oauth2'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider([])))), ($this->privates['Symfony\\Bridge\\PsrHttpMessage\\Factory\\PsrHttpFactory'] ?? $this->load('getPsrHttpFactoryService.php')));
