<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ7GtxN6\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ7GtxN6/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerJ7GtxN6.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerJ7GtxN6\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerJ7GtxN6\appAppKernelProdContainer([
    'container.build_hash' => 'J7GtxN6',
    'container.build_id' => '29cfd11b',
    'container.build_time' => 1714905088,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ7GtxN6');
